version: "3.8"

services:
  # Service 1: Backend FastAPI
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - lawrag-net

  # Service 2: Redis (Lưu trữ lịch sử chat)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - lawrag-net

networks:
  lawrag-net:
    driver: bridge
